version: '2'
services:
    ffbrw-app:
        image: ffbrw
        external_links:
            - ffbrw-mysql:mysql
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ffbrw?useUnicode=true&characterEncoding=utf8&useSSL=false
    ffbrw-mysql:
        extends:
            file: mysql.yml
            service: ffbrw-mysql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
